### PR TITLE
Add verifier role configurations; Updated policy.json policy file to ref...

### PR DESCRIPTION
**Pull request by jfwood**
...lect final RBAC assignments;

### CODE REVIEW

**Comment by stevendgonzales** [comment]
+1

There is no version bump in this pull request, but if this gets merged along with the other open pull request the code changes will be brought in with a new version

**Comment by stevendgonzales** [comment]
actually this PR will need a version bump as well

**Comment by jfwood** [comment]
Version bumped to 0.2.4 now Steven.

**Comment by stevendgonzales** [comment]
yay!

**Pull request merged**
