### PR TITLE
Increase the worker threadpool to 1000

### PR DESCRIPTION
**Pull request by dstufft**

### CODE REVIEW

**Comment by jfwood** [comment]
:+1:

**Comment by stevendgonzales** [comment]
We need to bump the cookbook version in the metadata.rb before we upload to Chef server

**Comment by stevendgonzales** [comment]
I went ahead and bumped the version on this repo directly

**Comment by dstufft** [comment]
Oh yea, I forgot about that. How does Chef even work!

**Comment by stevendgonzales** [comment]
Trust me @dstufft, you don't want to know....

**Pull request merged**
